config/routes.rb
Rails.application.routes.draw do
  root 'catalogs#index'
  get "/uploads" => "uploads#index"
  post "/uploads" => "uploads#create"
  resources :catalogs
  resources :products
  resources :catalogs do
    resources :products
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/catalog.rb
class Catalog < ApplicationRecord
  attr_accessor :select_type

  acts_as_nested_set #order_column: :name  before_add: :do_before_add_stuff 

  has_many :products, dependent: :delete_all #dependent: :destroy
  accepts_nested_attributes_for :products #, reject_if: :all_blank

  before_validation :normalize_numbers, on: :create

  # before_save :check_siblings
  after_commit :clear_cache #check_name_on_level

  validates :name, presence: true
  validates :element_type, presence: true
  validates :name, length: { maximum: 500, minimum: 2 }

  enum element_type: {
    product: 0,
    service: 10
  }

  private

  def clear_cache
    Rails.cache.clear
  end

  def normalize_numbers
    self.element_type = Integer(select_type) if select_type
  end

  scope :scope_sort, ->(sort) { includes(:products).where(depth: 0).order(name: sort).order(:lft) }
end

app/controllers/catalogs_controller.rb
# frozen_string_literal: true

class CatalogsController < ApplicationController
  before_action :set_catalog, only: %i[show edit update destroy upload]

  # GET /catalogs or /catalogs.json
  def index
    default_cookies unless cookies[:sort]

    cookies[:sort] = params[:sort] if params[:sort]
    @catalogs = Catalog.scope_sort(cookies[:sort])
  end

  def default_cookies
    cookies.permanent[:sort] = :asc
  end

  # GET /catalogs/1 or /catalogs/1.json
  def show; end

  # GET /catalogs/new
  def new
    @catalog = Catalog.new
  end

  # GET /catalogs/1/edit
  def edit; end

  # POST /catalogs or /catalogs.json
  def create
    @catalog = Catalog.new(catalog_params)
    return if check_siblings?(@catalog.parent_id, @catalog.name)

    respond_to do |format|
      if @catalog.save
        Rails.cache.clear
        Catalog.rebuild!
        format.html { redirect_to catalogs_path, notice: 'Catalog was successfully created.' }
        format.json { render :show, status: :created, location: @catalog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catalogs/1 or /catalogs/1.json
  def update
    respond_to do |format|
      if @catalog.update(catalog_params)
        Rails.cache.clear
        Catalog.rebuild!
        format.html { redirect_to catalogs_path, notice: 'Catalog was successfully updated.' }
        format.json { render :show, status: :ok, location: @catalog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @catalog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catalogs/1 or /catalogs/1.json
  def destroy
    @catalog.self_and_descendants.each do |item|
      Product.delete_by(catalog_id: item.id)
    end
    @catalog.destroy
    Rails.cache.clear
    Catalog.rebuild!
    respond_to do |format|
      format.html { redirect_to catalogs_path, notice: 'Catalog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def check_siblings?(parent_id, name)
    return true unless name

    if parent_id && Catalog.find(parent_id).children.map(&:name).include?(name)
      redirect_to new_catalog_path(catalog_id: parent_id), notice: 'В разделе только уникальные наименования!'
      return true
    elsif Catalog.where(depth: 0).map(&:name).include?(name) && parent_id.nil?
      redirect_to new_catalog_path(catalog_id: parent_id), notice: 'В корневом разделе только уникальные наименования!'
      return true
    end
    false
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_catalog
    @catalog = Catalog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def catalog_params
    params.require(:catalog).permit(:parent_id, :name, :element_type, :will_remove, :select_type, :sort, :import_cvs)
  end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/views/catalogs/_form.html.slim
div id = 'new_catalog' class = 'mb-3' style ='margin: 10px; width: fit-content'
  .warning
    = flash[:notice]
  table.table.table.thead-dark.table-bordered id = 'table_form'
    thead
      = form_for @catalog do |f|
        .field
          tr 
            td colspan="2"
              h3 = head
          tbody
            tr
              td = f.label 'Родительский элемент', class: 'form-label'
              - if params[:catalog_id]
                td = f.select :parent_id, options_for_select([[Catalog.find_by(id: params[:catalog_id]).name , params[:catalog_id]]]), class: "form-select", id:"select_parent_id"
              - else
                td = f.select :parent_id, nested_set_options(Catalog.except(:order).order(:name)) {|i| "#{'-' * i.level} #{i.name}"}, include_blank: true, class: "form-select", id:"select_parent_id"
            tr
              td = f.label 'Наименование папки', class: 'form-label'
              td = f.text_field :name, class: 'form-control form-control-sm'
            tr
              td = f.label 'Тип', class: 'form-label'
              td = f.select :select_type, options_for_select([['poduct', 0 ], ['service', 10]]), class: "form-select form-select-lg mb-3", id:"select_type"
            tr
              td = f.submit "Сохранить", class: 'btn btn-secondary'
              td = link_to t('Назад'), url_for(:back), data: { turbolinks: false }, class: 'btn btn-secondary'
    

app/views/catalogs/_nested_fields.html.slim
- catalogs.each do |item|
  - if item.root?
    .catalog-folder
      = link_to "#{item.leaf? || !item.products ? '' : '- '} #{item.name}", edit_catalog_path(item), data: { turbolinks: false }, class: 'folder-link'
      = form_tag catalogs_path, method: :post, class: 'catalog-buttons-form'
        = link_to 'Создать подраздел', new_catalog_path(catalog_id: item.id), data: { turbolinks: false }, class: 'delete-link'
        = link_to 'Создать товар', new_product_path(catalog_id: item.id), data: { turbolinks: false }, class: 'delete-link'
      = link_to ' Удалить', catalog_path(item), method: :delete, data: {confirm: "Удалить #{item.name} ? Вы уверены?", turbolinks: false}, class: 'delete-link'
      - if item.root? && item.descendants
        - @root_product = item
        = render "catalogs/nested_fields", catalogs: item.children.except(:order).order(:name), cached: true
      - if item.products
        = render "catalogs/products_list", products: item.products.order(name: cookies[:sort]), cached: true
        - @root_product = nil
  - else  
    .catalog-folder
      - if !@array_catalog.include?(item.id)
        = link_to "#{item.products.count.positive? || !item.leaf? ? '- ' : ''} #{item.name}", edit_catalog_path(item), data: { turbolinks: false }, class: 'folder-link'
        = form_tag catalogs_path, method: :post, class: 'catalog-buttons-form'
          = link_to 'Создать подраздел', new_catalog_path(catalog_id: item.id), data: { turbolinks: false }, class: 'delete-link'
          = link_to 'Создать товар', new_product_path(catalog_id: item.id), data: { turbolinks: false }, class: 'delete-link'
        = link_to ' Удалить', catalog_path(item), method: :delete, data: {confirm: "Удалить #{item.name} ? Вы уверены?", turbolinks: false}, class: 'delete-link'
        - @array_catalog.push(item.id)
        - if item.descendants
          - @root_product = item
          = render "catalogs/nested_fields", catalogs: item.children.except(:order).order(:name), cached: true
        - elsif item.products
          = render "catalogs/products_list", products: @root_product.products.order(name: cookies[:sort]), cached: true
          - @root_product = nil
        - if item.products
          = render "catalogs/products_list", products: item.products.order(name: cookies[:sort]), cached: true
  / - if item.leaf?
  /   = render "catalogs/products_list", products: item.products
  / - else
  /   = render "catalogs/nested_fields", catalogs: item.children.except(:order).order(:name), cached: true
      

app/views/catalogs/_products_list.html.slim
- products.each do |product|
  - if !@array_product.include?(product.id)
    .catalog-product
      = link_to "#{product.name} - #{product.price} руб.", edit_product_path(product), data: { turbolinks: false }, class: 'product-link', title: "#{product.specification}"
      = link_to ' Удалить', product_path(product), method: :delete, data: {confirm: "Удалить #{product.name} ? Вы уверены?",  turbolinks: false}, class: 'delete-link'
      - @array_product.push(product.id)   

app/views/catalogs/edit.html.slim
div class = 'mb-3' style ='margin-left: 15px;'
  div class = 'mb-3' style ='margin-left: 10px;'
  - if @catalog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@catalog.errors.count, 'error')} prohibited this event from being saved:"
      ul
        - @catalog.errors.full_messages.each do |message|
          li = message
  = render 'form', catalog: @catalog, head: 'ИЗМЕНИТЬ ЭЛЕМЕНТ КАТАЛОГА'

/= link_to 'Show', @catalog

/= link_to 'Delete', catalog_path(@catalog), method: :delete, data: {confirm: "Удалить #{@catalog.name} ? Вы уверены?"}

app/views/catalogs/index.html.slim
.container-fluid
  h2 Каталог
  p
  .actions
    = form_tag catalogs_path, method: :post, class: 'catalog-buttons-form', multipart: true
      = link_to 'Создать раздел', new_catalog_path, action: :new, data: { turbolinks: false }, class: 'catalog-button-link', notice:''
      = link_to 'Создать товар', new_product_path, action: :new, data: { turbolinks: false }, class: 'catalog-button-link', notice:''
      /= form_tag catalogs_path, method: :post, class: 'catalog-buttons-form', multipart: true
      = link_to 'А-Я', catalogs_path(sort: :asc), data: { turbolinks: false }, class: 'catalog-button-link'
      = link_to 'Я-А', catalogs_path(sort: :desc), data: { turbolinks: false }, class: 'catalog-button-link'
  = link_to 'Загрузить каталог', uploads_path, class: 'catalog-button-link', notice:''
  p
  - @root_product = nil
  - @array_catalog = []
  - @array_product = []
  - @catalogs.each do |catalog|
    - cache catalog do
      = render "nested_fields", catalogs: [catalog], cached: true     

app/views/catalogs/new.html.slim
div class = 'mb-3' style ='margin-left: 15px;'
  div class = 'mb-3' style ='margin-left: 10px;'
  - if @catalog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@catalog.errors.count, 'error')} prohibited this event from being saved:"
      ul
        - @catalog.errors.full_messages.each do |message|
          li = message
  = render 'form', head: "НОВЫЙ ЭЛЕМЕНТ КАТАЛОГА"

  / div class = 'mb-3' style ='margin-left: 15px;'
  /   = link_to 'Back', catalogs_path, class: 'btn btn-primary'

app/views/catalogs/old_index.html.slim
div id = 'table_view' class = 'mb-3' style ='margin: 10px;'
  p КАТАЛОГ
  table.table.table-striped class ='table table-striped' style ='margin: 5px;'
    thead
      tr
        th id
        th Родитель
        th Название
        th Тип
        th Изменить
        th Удалить
    tbody
      - @catalogs.order(name: :asc).each do |element|
        tr
          td = element.id
          td = element.parent_id
          td = element.name
          td = element.element_type
          td = link_to 'edit', edit_catalog_path(element)
          td = link_to 'destroy', element, data: { confirm: 'Are you sure?' }, method: :delete

= select_tag 'parent_id', options_for_select(nested_set_options(Catalog) {|i| "#{'-' * i.level} #{i.name}" } )
= nested_set_options(Catalog) {|i| "#{'-' * i.level} #{i.name}" }
- if @catalogs
  p
    strong Comments:
    - Catalog.order(:depth, :lft).each_with_level(@catalogs) do |element, level|
      p(style="padding-left:#{level * 20}px")
        = "#{level} -- #{element.name}"

app/views/catalogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_catalog_path(@catalog) %> |
<%= link_to 'Back', catalogs_path %>